// This file was generated by RedwoodJS
import { Success } from './EditUserExampleCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditUserExampleById, EditUserExampleByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditUserExampleCell'

type CellInputs = CellProps<SuccessType, EditUserExampleById, EditUserExampleByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
