// This file was generated by RedwoodJS
import { Success } from './VideosCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindVideos, FindVideosVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './VideosCell'

type CellInputs = CellProps<SuccessType, FindVideos, FindVideosVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
