// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/NotFoundPage/NotFoundPage'
import VideoEditVideoPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/Video/EditVideoPage/EditVideoPage'
import VideoNewVideoPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/Video/NewVideoPage/NewVideoPage'
import VideoVideoPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/Video/VideoPage/VideoPage'
import VideoVideosPageType from '/Users/hygorzorak/Development/redwood-test/web/src/pages/Video/VideosPage/VideosPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const VideoEditVideoPage: typeof VideoEditVideoPageType
  const VideoNewVideoPage: typeof VideoNewVideoPageType
  const VideoVideoPage: typeof VideoVideoPageType
  const VideoVideosPage: typeof VideoVideosPageType
}
