// This file was generated by RedwoodJS
import { Success } from './UserExamplesCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindUserExamples, FindUserExamplesVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './UserExamplesCell'

type CellInputs = CellProps<SuccessType, FindUserExamples, FindUserExamplesVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
