// This file was generated by RedwoodJS
import { Success } from './VideoCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindVideoById, FindVideoByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './VideoCell'

type CellInputs = CellProps<SuccessType, FindVideoById, FindVideoByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
