// This file was generated by RedwoodJS
import { Success } from './VideoListCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindVideoListQuery, FindVideoListQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './VideoListCell'

type CellInputs = CellProps<SuccessType, FindVideoListQuery, FindVideoListQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
