// This file was generated by RedwoodJS
import { Success } from './UserExampleCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindUserExampleById, FindUserExampleByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './UserExampleCell'

type CellInputs = CellProps<SuccessType, FindUserExampleById, FindUserExampleByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
