// This file was generated by RedwoodJS
import { Success } from './VideosCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindVideosQuery, FindVideosQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './VideosCell'

type CellInputs = CellProps<SuccessType, FindVideosQuery, FindVideosQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
