// This file was generated by RedwoodJS
import { Success } from './EditVideoCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditVideoById, EditVideoByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditVideoCell'

type CellInputs = CellProps<SuccessType, EditVideoById, EditVideoByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
